### ISSUE TITLE
Will it work on Binary images

### ISSUE THREAD

**Issue by ShakirKhurshid** [yongzx/PyTorch-PaletteNet#2]
Will it work on Binary images (having pixel values 0 and 1 for white and black respectively)

**Comment by yongzx** [comment]
I haven't tried it out yet, but if you have the data, please try it out. I believe it should work as long as palette is given because the palettes are needed for the upsampling layers.

**Comment by ShakirKhurshid** [comment]
Sure, will do. But Generating a palette for a Binary image seems an issue, as it only have two colours and in the paper its mentioned we require 6 colour palette. But still, gonna try it out.

**Comment by yongzx** [comment]
You are right. I am not sure whether the PaletteNet will work on only 2 colors, but one quick hack is to reduce the color palette to 2 and try it out. I think in my implementation, I hardcoded the dimension of the color palette `target_palettes = torch.ones(bz, 18, h, w).float().to(device)`.
