### ISSUE TITLE
Change the output resolution

### ISSUE THREAD

**Issue by ShakirKhurshid** [yongzx/PyTorch-PaletteNet#5]
Can you suggest  a good way of changing the resolution of the output image.

**Comment by yongzx** [comment]
Hey Shakir, can you expand your question a little bit? What do you mean by changing the resolution of the output image?

**Comment by tsz12** [comment]
Can you provide the dataset, I would thank you for that very much.

**Comment by yongzx** [comment]
@tsz12 See #1 and #3.

Closing this thread due to inactivity.

**Comment by tsz12** [comment]
Hello,thank you for your reply. If you can't provide the dataset, can I know the format of the data? Just the screenshot is enough. Or could you tell me how to get the plalette, as we can't see where it is on the drrible.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yong ***@***.***&gt;; 
发送时间: 2022年1月12日(星期三) 晚上11:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yongzx/PaletteNet-PyTorch] Change the output resolution (#5)





 
@tsz12 See #1 and #3.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tsz12** [comment]
A little data is enough, I just want to run the code&nbsp;successfully. Thank you again!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yong ***@***.***&gt;; 
发送时间: 2022年1月12日(星期三) 晚上11:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yongzx/PaletteNet-PyTorch] Change the output resolution (#5)





 
@tsz12 See #1 and #3.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yongzx** [comment]
Here's some data: https://github.com/yongzx/PaletteNet-PyTorch/blob/master/example_dribbble_designs.tsv

**Comment by tsz12** [comment]
Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yongzx/PaletteNet-PyTorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月12日(星期三) 晚上11:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yongzx/PaletteNet-PyTorch] Change the output resolution (#5)





 
Here's some data: https://github.com/yongzx/PaletteNet-PyTorch/blob/master/example_dribbble_designs.tsv
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yongzx** [comment]
Media paths and urls might no longer work because it seems like Dribbble has redesigned their websites, where color palettes are no longer retrievable.
